const exams=[
['Ácido úrico','$3,30'],['Albúmina','$3,30'],['Amilasa','$4,00'],['Aglutinaciones febriles','$7,00'],['ASTO - Antiestreptolisina','$8,80'],['Alfa feto proteínas - AFP','$13,28'],['Ácido fólico','$13,00'],['ACTIN F. IgA / ACTIN','$28,60'],['ACTIN IgG','$28,60'],['ANCA C-P','$40,00'],['ASCA IgG','$25,50'],['ASCA IgA','$25,50'],['Antitrombina','$39,61'],['Apolipoproteína A1','$15,40'],['Apolipoproteína B','$9,36'],['BUN (incluye urea)','$6,09'],['Creatinina','$3,30'],['Colesterol total','$3,30'],['Colesterol HDL','$5,50'],['Colesterol LDL','$5,60'],['Coprocultivo (heces)','$22,00'],['Calcio','$4,00'],['CA 125 (ovario, útero)','$15,40'],['Ceruloplasmina','$35,07'],['Calprotectina','$36,40'],['Calcio iónico','$8,00'],['Cloro','$3,38'],['Cardiolipina IgG','$24,44'],['Cardiolipina IgM','$24,44'],['CK MB-CPK','$13,52'],['Creatinina (orina)','$6,09'],['Colinesterasa','$4,40'],['Interleukina 6','$34,00'],['Insulina plasmática en ayunas','$14,30'],['IgG por nefelometría','$16,00'],['IgM por nefelometría','$17,00'],['IgA por nefelometría','$17,00'],['IgE total','$16,00'],['Influenza A/B/H1N1 por PCR GeneXpert','$188,37'],['Influenza A/B antígeno','$28,00'],['Insulina 2h post prandial','$34,00'],['KOH','$13,20'],['Kappa (orina)','$27,63'],['Kappa 24h','$28,60'],['Lipasa','$4,40'],['LDH (deshidrogenasa láctica)','$4,40'],['Linfocitos B (CD19-CD20)','$80,00'],['Linfocitos NK (CD16-CD56)','$48,30'],['Lipoproteína A','$16,00'],['Litio','$16,00'],['Lactoferrina','$20,00'],['Norovirus','$40,00'],['Osmolalidad','$14,49'],['Osteocalcina','$50,72'],['Oxalato urinario','$46,20'],['Opiáceos cuantitativa','$11,59'],['Plaquetas','$6,00'],['Prueba de Coombs directa','$9,00'],['Prueba de Coombs indirecta','$9,00'],['Parasitoscópico concentración (heces)','$6,00'],['PSA total','$16,93'],['PSA libre','$25,30'],['Potasio','$4,00'],['Pro-BNP','$65,00'],['Procalcitonina','$74,38'],['Prealbúmina','$30,00'],['Prolactina','$12,00'],['Progesterona','$12,00'],['Rotavirus','$13,00'],['R. de Widal y Weill Felix','$7,00'],['Factor reumatoideo por nefelometría','$16,00'],['RPR','$5,00'],['Rubeola IgG','$16,72'],['Rubeola IgM','$16,72'],['Sangre oculta - HB humana','$7,10'],['Sodio','$4,00'],['Sodio (orina)','$4,00'],['Strept-A','$13,20'],['Salmonella antígeno','$14,00'],['Urea','$3,30'],['Urocultivo (orina)','$18,00'],['Urea 24h','$6,30'],['V.D.R.L.','$5,50'],['Vitamina B12','$13,00'],['VLDL colesterol','$6,30'],['V.D.R.L. cuantitativo','$9,00'],['Varicela zóster IgG','$28,00'],['Varicela zóster IgM','$21,25'],['Vitamina D total','$32,00'],['Vitamina E','$65,10'],['Virus sincitial respiratorio','$36,75'],['Ziehl Neelsen','$7,20'],['Zinc','$35,00'],['Zika virus IgG','$100,49'],['Zika virus IgM','$75,74']
].map(([name,price])=>({name,price}));
const notes=[
{slug:'el-estres-un-enemigo-silencioso-que-afecta-nuestra-salud-fisica-y-mental',title:'El estrés: Un enemigo silencioso que afecta nuestra salud física y mental',date:'07 Nov',tag:'Labs · Salud',img:'assets/labs-inicio-2.jpeg',intro:'La Organización Mundial de la Salud (OMS) define el estrés como cualquier tipo de cambio que provoca agotamiento físico, emocional o psicológico.',body:[`La Organización Mundial de la Salud (OMS) define el estrés como cualquier tipo de cambio que provoca agotamiento físico, emocional o psicológico. Según la entidad, se trata de una respuesta natural del cuerpo humano ante situaciones que requieren una acción rápida.`,`Aunque el estrés puede surgir frente a cualquier desafío, es un fenómeno cotidiano en la vida moderna. Cuando se convierte en algo crónico puede tener repercusiones en la salud.`,`El cuerpo reacciona al estrés liberando hormonas como el cortisol, que activan el estado de alerta, tensionan los músculos y aceleran la respiración y el ritmo cardíaco. Dolores de cabeza, malestar estomacal, dolor de espalda e insomnio son algunas de sus manifestaciones.`,`Para evaluar su impacto, LABS señala la utilidad de perfiles hormonales y pruebas específicas, siempre dentro de una evaluación médica.`,`Aprender a manejar el estrés mejora la calidad de vida. El ejercicio regular, las técnicas de relajación y actividades que generen bienestar pueden ayudar a reducir la tensión.`]},
{slug:'higado-el-filtro-natural-del-cuerpo',title:'Hígado, el «filtro» natural del cuerpo',date:'05 Sep',tag:'Hígado · Labs',img:'assets/labs-inicio-1.jpeg',intro:'Mantenerlo sano a través de una buena alimentación es vital.',body:[`El hígado, un órgano esencial, tiene un papel crucial en la actividad metabólica. Se ubica en la parte superior derecha de la cavidad abdominal y cumple funciones vitales para el bienestar general.`,`Es responsable de regular sustancias químicas en la sangre, producir bilis y procesar sustancias que llegan desde el aparato digestivo.`,`Principales funciones del hígado: eliminación de toxinas, metabolización de medicamentos, secreción de bilis y almacenamiento de nutrientes.`,`La prevención es clave. Una alimentación equilibrada, moderar el consumo de grasas y alimentos procesados, evitar el exceso de alcohol y mantener actividad física son medidas importantes.`,`En LABS se puede realizar una prueba de función hepática para evaluar proteínas, bilirrubinas y enzimas hepáticas, de acuerdo con la indicación médica.`]},
{slug:'rinones-los-heroes-ocultos-de-nuestro-cuerpo',title:'Riñones: los héroes ocultos de nuestro cuerpo',date:'23 Jul',tag:'Labs',img:'assets/labs-inicio-2.jpeg',intro:'La hidratación, el ejercicio y una alimentación baja en sal son fundamentales para su cuidado.',body:[`Los riñones son dos órganos con una tarea primordial: filtrar la sangre y eliminar desechos. También participan en funciones hormonales y en el equilibrio del organismo.`,`Cada día filtran grandes cantidades de sangre para producir orina y ayudar a mantener el equilibrio de agua y minerales.`,`Los malos hábitos pueden afectar la salud renal. Entre ellos están una dieta alta en sal, ingerir demasiada azúcar, fumar, beber poca agua, la inactividad física y el consumo excesivo de alcohol.`,`Los exámenes de sangre y orina permiten evaluar el funcionamiento renal. Entre los análisis mencionados por LABS están creatinina, BUN, cistatina C y evaluaciones de proteínas en orina.`]},
{slug:'4-sintomas-que-debes-saber-sobre-el-dengue',title:'4 síntomas que debes saber sobre el dengue',date:'05 Mar',tag:'Labs · Nacionales',img:'assets/labs-inicio-2.jpeg',intro:'Fiebre alta, dolor de cabeza, dolor muscular y molestias detrás de los ojos son síntomas que requieren atención.',body:[`Los cuatro síntomas destacados son fiebre alta, dolor de cabeza, dolor muscular y molestias detrás de los ojos. Ante síntomas compatibles es importante acudir a un médico y evitar la automedicación.`,`Las pruebas de laboratorio desempeñan un papel fundamental en el diagnóstico preciso del dengue. LABS cuenta con pruebas específicas como Dengue anti IgG, Dengue anti IgM y antígeno NS1, según la indicación médica.`,`Las medidas preventivas incluyen eliminar aguas estancadas, usar repelentes, instalar mosquiteros y acudir a consulta ante la presencia de síntomas.`,`La prevención, la detección temprana y el tratamiento adecuado son herramientas importantes en la lucha contra el dengue.`]},
{slug:'perdiendo-peso-que-examenes-de-laboratorio-necesito',title:'Perdiendo peso, ¿qué exámenes de laboratorio necesito?',date:'05 Feb',tag:'Exámenes · Labs · Salud',img:'assets/labs-inicio-1.jpeg',intro:'Bajar de peso de manera saludable requiere prevención, alimentación equilibrada, ejercicio y seguimiento médico.',body:[`La medicina preventiva juega un papel importante. Los chequeos y exámenes básicos de sangre, heces y orina pueden aportar información sobre el estado del organismo.`,`Un estilo de vida saludable combina dieta equilibrada, ejercicio regular y controles médicos periódicos.`,`Los análisis clínicos pueden revelar aspectos como niveles de glucosa, perfil lipídico e intolerancias alimentarias, entre otros indicadores.`,`Los resultados deben interpretarse con el acompañamiento de profesionales de la salud.`]},
{slug:'7-examenes-basicos-que-debes-realizarte-en-el-ano',title:'7 exámenes básicos que debes realizarte en el año',date:'19 Ene',tag:'Exámenes · Labs · Salud',img:'assets/labs-inicio-1.jpeg',intro:'Los chequeos preventivos y análisis completos aportan información valiosa sobre el estado general de salud.',body:[`El hemograma completo evalúa las células sanguíneas y es uno de los análisis básicos más habituales.`,`El perfil lipídico permite conocer niveles de colesterol y triglicéridos. La glucosa en sangre está relacionada con la detección y control de diabetes.`,`Los marcadores inflamatorios aportan información sobre la presencia de inflamación. También pueden evaluarse vitaminas y minerales.`,`El elemental físico químico de orina y el coproparasitario forman parte de los análisis básicos descritos por LABS.`,`La preparación depende del examen y debe seguir las indicaciones del laboratorio y del profesional de salud.`]},
{slug:'estres-dolor-abdominal-gases-estrenimiento',title:'¿Cómo los exámenes revelan el impacto del estrés en tu salud?',date:'11 Ene',tag:'Exámenes · Labs · Salud',img:'assets/labs-inicio-2.jpeg',intro:'Los niveles altos de estrés pueden relacionarse con trastornos gastrointestinales y otros síntomas.',body:[`Entre los síntomas descritos están hinchazón abdominal, dolor de estómago, estreñimiento, opresión estomacal, falta de apetito y dispepsia.`,`La evaluación médica puede acompañarse de grupos de exámenes como cortisol, perfil hormonal, muestras fecales, pruebas de inflamación, función hepática y nutrientes.`,`La combinación de estas pruebas puede brindar al especialista información para valorar el estado de salud gastrointestinal.`]},
{slug:'que-se-puede-ver-en-un-hemograma',title:'¿Qué se puede ver en un hemograma?',date:'22 Dic',tag:'Exámenes · Labs · Salud',img:'assets/labs-inicio-1.jpeg',intro:'El hemograma es uno de los análisis más comunes y aporta información sobre las células sanguíneas.',body:[`El hemograma permite observar el comportamiento de glóbulos rojos, glóbulos blancos y plaquetas. Estos parámetros ayudan a valorar distintas condiciones.`,`Realizarse controles puede contribuir a identificar alteraciones en etapas tempranas. La interpretación debe estar a cargo de un médico.`,`Para realizar un hemograma se requiere una muestra de sangre y, según la información publicada por LABS, no es necesario estar en ayunas.`]},
{slug:'los-examenes-de-laboratorio-son-necesarios-y-primordiales',title:'Los exámenes de laboratorio son necesarios y primordiales',date:'15 Dic',tag:'Labs · Salud',img:'assets/labs-inicio-2.jpeg',intro:'Las pruebas de laboratorio aportan información para el diagnóstico, seguimiento y prevención.',body:[`Los exámenes de laboratorio se realizan a partir de muestras como sangre, orina y heces, y pueden ayudar a descubrir diversas afecciones.`,`Las pruebas diagnósticas son una herramienta de apoyo para las decisiones médicas y permiten evaluar diferentes aspectos fisiológicos y bioquímicos.`,`La variedad de exámenes disponibles permite personalizar el enfoque de atención y contribuir a la prevención y manejo de distintas afecciones.`]},
{slug:'el-vih-y-el-sida-son-lo-mismo',title:'¿El VIH y el SIDA son lo mismo?',date:'01 Dic',tag:'Exámenes · Labs · Salud',img:'assets/labs-inicio-1.jpeg',intro:'VIH y SIDA están relacionados, pero no significan lo mismo.',body:[`El VIH es el virus que causa la infección, mientras que el SIDA es un síndrome que puede aparecer en una etapa avanzada de la infección.`,`El virus puede transmitirse mediante determinados fluidos corporales y existen vías de transmisión sexual, sanguínea y vertical.`,`Los exámenes de laboratorio son importantes para detectar y hacer seguimiento de la infección y de la respuesta al tratamiento.`]}
];

const examsSearch=exams.map((x,i)=>({...x,id:i}));
const state={selected:new Set()};
const money=s=>Number(String(s).replace('$','').replace(',','.'));
const fmt=n=>'$'+n.toFixed(2).replace('.',',');
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
const I18N={
 es:{
  topBrand:'HUMANLABS · MEDICINA DIAGNÓSTICA',navHome:'Inicio',navAbout:'Nosotros',navNotes:'Notas de salud',navContact:'Contacto',navQuote:'Cotizador de exámenes',login:'Login',
  heroEyebrow:'HUMANLABS · MEDICINA DIAGNÓSTICA',heroTitle:'Su laboratorio de confianza.',heroLead:'Servicios de análisis y diagnósticos clínicos confiables, oportunos y orientados al bienestar de nuestros pacientes.',heroCta:'Conoce más sobre LABS',heroEyebrow2:'CALIDAD · TECNOLOGÍA · CONFIANZA',heroTitle2:'Resultados que ayudan a cuidar tu salud.',heroLead2:'Contamos con tecnología para la toma y procesamiento de muestras y profesionales comprometidos con la calidad.',heroCta2:'Encuentra una sede',
  homeKicker:'HUMANLABS',homeTitle:'Medicina diagnóstica con confianza.',homeLead:'HUMANLABS Medicina Diagnóstica se establece con el fin de brindar el mejor y más completo servicio de exámenes de laboratorio. Trabajamos con calidad, calidez, puntualidad y rigurosas normas de confidencialidad.',homeCta:'Conoce más sobre nosotros',
  aboutHeroTitle:'HUMANLABS MEDICINA DIAGNÓSTICA',aboutHeroLead:'Su laboratorio de confianza.',aboutKicker:'ACERCA DE NOSOTROS',aboutTitle:'Su laboratorio de confianza.',aboutIntro:'HUMANLABS MEDICINA DIAGNÓSTICA se establece con el fin de brindar el mejor y más completo servicio de exámenes de laboratorio a los ciudadanos de la ciudad de Guayaquil.',missionLabel:'Misión:',missionText:'Somos un laboratorio que cuenta con tecnología para la toma y procesamiento de muestras. Otorgamos servicios de análisis y diagnósticos clínicos confiables, oportunos con altos niveles de ética y calidad. Mediante la calidad de nuestro servicio, brindamos apoyo a los médicos y empresas que confían en los resultados que entregamos, a fin de buscar soluciones tempranas que ayuden al bienestar del paciente.',visionLabel:'Visión:',visionText:'Ampliar la cartera de exámenes clínicos para ofrecer un servicio más completo, aumentar la satisfacción de nuestros pacientes y de esta manera, llegar a ser un laboratorio referente a nivel nacional con presencia en puntos estratégicos del país.',scopeTitle:'Alcance',scopeText:'Proceso de análisis clínico en sus etapas pre-analítico, analítico, post analítico en las líneas de hematología, coagulación, química clínica, hormonas, uroanálisis y parasitología aplicadas a Laboratorio Central.',qualityTitle:'Política de Calidad',qualityText:'Somos un laboratorio clínico confiable que trabaja con calidad, calidez, puntualidad y rigurosas normas de confidencialidad en cada uno de los procesos ejecutados. Nuestro personal capacitado trabaja comprometido con nuestros pacientes, para entregar información clínicamente útil para la toma de decisiones médicas.',continuousTitle:'Mejora continua',continuousText:'En Humanlabs estamos comprometidos con el cumplimiento de los requisitos de nuestras partes interesadas, mediante la mejora continua y cumplimiento de nuestros objetivos.',
  contactHeroTitle:'Contactos',contactHeroLead:'HUMANLABS siempre cerca de ti.',locationsKicker:'ENCUÉNTRANOS EN TU CIUDAD',locationsTitle:'Nuestras sedes',guayaquil:'Guayaquil',principal:'Sede Principal',gyeAddress:'Av. Abel Romeo Castillo y Juan Tanca Marengo, Torre Médica 2, piso 4, consultorios 417 y 418.',gyeHours:'LUN–VIE 06h30–18h00 · SAB 06h30–12h00',quito:'Quito',quitoAddress:'Av. Mariana de Jesús OE7-02 y Nuño de Valderrama. Edificio CITIMED Planta Baja Local 7.',quitoHours:'LUN–VIE 07h00–16h00',manta:'Manta',mantaAddress:'Edificio Umiñamed, planta baja (misma sede de EndoscopyNet Manta).',mantaHours:'LUN–VIE 07h00–15h40',santoDomingo:'Santo Domingo',santoAddress:'Av. Quito, entre Latacunga e Ibarra.',santoHours:'LUN–VIE 07h30–16h10',milagro:'Milagro',milagroAddress:'Calle 17 de Septiembre, entre Calle Esmeraldas y Guayas, frente a CNEL.',milagroHours:'LUN–VIE 08h00–16h00',hoursLabel:'Horario:',hoursLabel2:'Horario:',hoursLabel3:'Horario:',hoursLabel4:'Horario:',hoursLabel5:'Horario:',contactKicker:'CONTACTO',contactTitle:'Estamos para ayudarte.',nationalCall:'Call Center Nacional:',whatsappWrite:'Escribir en WhatsApp',emailWrite:'Enviar correo',
  backToNotes:'Volver a Notas de salud',newsHeroTitle:'Notas de salud',newsHeroLead:'Contenido educativo de LABS para pacientes y familias.',searchPlaceholder:'Buscar aquí',searchButton:'Buscar',noResults:'No encontramos contenidos con ese término.',
  quotePageTitle:'Cotizador de exámenes',quotePageLead:'Busca, selecciona tus exámenes y genera una cotización en PDF.',quoteKicker:'COTIZADOR DE EXÁMENES',quoteTitle:'Consulta y cotiza tus exámenes.',quoteIntro:'Busca un examen, agrégalo individualmente a tu cotización y revisa el total automáticamente.',examSearchPlaceholder:'Buscar examen por nombre',clearSearch:'Limpiar',selectedTitle:'Exámenes seleccionados',selectedLabel:'seleccionados',totalLabel:'TOTAL',clientData:'Datos del cliente',fullName:'Nombre completo',idNumber:'Cédula',email:'Correo electrónico',phone:'Teléfono',generatePdf:'GENERAR COTIZACIÓN PDF',pdfNote:'El PDF incluirá los exámenes seleccionados, precios, total, fecha y tus datos.',add:'Agregar',added:'Agregado',remove:'Eliminar',emptySelected:'Aún no has agregado exámenes.',noExams:'No encontramos exámenes con ese nombre.',
  footerNear:'HUMANLABS siempre cerca de ti.',footerExplore:'EXPLORA',footerLabs:'LABS',footerWho:'Quiénes somos',footerLocations:'Sedes',footerContact:'CONTACTO',whatsapp:'WhatsApp',copyright:'© 2026 HUMANLABS. Todos los Derechos Reservados',diagnostics:'Medicina Diagnóstica',privacyTitle:'Privacidad',privacyText:'Este sitio utiliza cookies necesarias para funcionar y cookies opcionales para mejorar la experiencia.',saveCookies:'GUARDAR Y ACEPTAR',
  pdfTitle:'COTIZACIÓN DE EXÁMENES',pdfClient:'DATOS DEL CLIENTE',pdfExam:'EXAMEN',pdfPrice:'PRECIO',pdfTotal:'TOTAL',pdfDisclaimer:'Este documento corresponde a una solicitud de cotización y no constituye una factura fiscal.',pdfConfirm:'Precios mostrados según el catálogo de cotización utilizado por este sitio; confirme condiciones con LABS.',pdfGenerated:'PDF generado correctamente.',pdfLoad:'No se pudo cargar el generador PDF. Revisa tu conexión a internet.',
  alertName:'Ingresa tu nombre completo.',alertCedula:'La cédula debe contener 10 dígitos.',alertEmail:'Ingresa un correo electrónico válido.',alertPhone:'Ingresa un teléfono válido.',alertExam:'Agrega al menos un examen a la cotización.'
 },
 en:{
  topBrand:'HUMANLABS · DIAGNOSTIC MEDICINE',navHome:'Home',navAbout:'About us',navNotes:'Health notes',navContact:'Contact',navQuote:'Test quote',login:'Login',
  heroEyebrow:'HUMANLABS · DIAGNOSTIC MEDICINE',heroTitle:'Your trusted laboratory.',heroLead:'Reliable and timely clinical analysis and diagnostic services focused on the wellbeing of our patients.',heroCta:'Learn more about LABS',heroEyebrow2:'QUALITY · TECHNOLOGY · TRUST',heroTitle2:'Results that help care for your health.',heroLead2:'We have technology for sample collection and processing, supported by professionals committed to quality.',heroCta2:'Find a location',
  homeKicker:'HUMANLABS',homeTitle:'Diagnostic medicine you can trust.',homeLead:'HUMANLABS Diagnostic Medicine was established to provide citizens with the best and most complete laboratory testing service. We work with quality, warmth, punctuality and strict confidentiality standards.',homeCta:'Learn more about us',
  aboutHeroTitle:'HUMANLABS DIAGNOSTIC MEDICINE',aboutHeroLead:'Your trusted laboratory.',aboutKicker:'ABOUT US',aboutTitle:'Your trusted laboratory.',aboutIntro:'HUMANLABS DIAGNOSTIC MEDICINE was established to provide citizens of Guayaquil with the best and most complete laboratory testing service.',missionLabel:'Mission:',missionText:'We are a laboratory equipped with technology for sample collection and processing. We provide reliable and timely clinical analysis and diagnostic services with high standards of ethics and quality. Through the quality of our service, we support physicians and companies that trust our results, seeking early solutions that contribute to patient wellbeing.',visionLabel:'Vision:',visionText:'Expand our clinical test portfolio to offer a more complete service, increase patient satisfaction and become a nationally recognized laboratory with a presence in strategic locations throughout the country.',scopeTitle:'Scope',scopeText:'Clinical analysis processes in the pre-analytical, analytical and post-analytical stages in hematology, coagulation, clinical chemistry, hormones, urinalysis and parasitology applied at the Central Laboratory.',qualityTitle:'Quality Policy',qualityText:'We are a reliable clinical laboratory that works with quality, warmth, punctuality and strict confidentiality standards in every process. Our trained staff are committed to our patients and to providing clinically useful information for medical decision-making.',continuousTitle:'Continuous improvement',continuousText:'At Humanlabs we are committed to meeting stakeholder requirements through continuous improvement and fulfillment of our objectives.',
  contactHeroTitle:'Contact',contactHeroLead:'HUMANLABS is always close to you.',locationsKicker:'FIND US IN YOUR CITY',locationsTitle:'Our locations',guayaquil:'Guayaquil',principal:'Main Location',gyeAddress:'Av. Abel Romeo Castillo and Juan Tanca Marengo, Torre Médica 2, 4th floor, offices 417 and 418.',gyeHours:'MON–FRI 06:30–18:00 · SAT 06:30–12:00',quito:'Quito',quitoAddress:'Av. Mariana de Jesús OE7-02 and Nuño de Valderrama. CITIMED Building, Ground Floor, Local 7.',quitoHours:'MON–FRI 07:00–16:00',manta:'Manta',mantaAddress:'Umiñamed Building, ground floor (same location as EndoscopyNet Manta).',mantaHours:'MON–FRI 07:00–15:40',santoDomingo:'Santo Domingo',santoAddress:'Av. Quito, between Latacunga and Ibarra.',santoHours:'MON–FRI 07:30–16:10',milagro:'Milagro',milagroAddress:'17 de Septiembre Street, between Esmeraldas and Guayas, opposite CNEL.',milagroHours:'MON–FRI 08:00–16:00',hoursLabel:'Hours:',hoursLabel2:'Hours:',hoursLabel3:'Hours:',hoursLabel4:'Hours:',hoursLabel5:'Hours:',contactKicker:'CONTACT',contactTitle:'We are here to help.',nationalCall:'National Call Center:',whatsappWrite:'Write on WhatsApp',emailWrite:'Send email',
  backToNotes:'Back to health notes',newsHeroTitle:'Health notes',newsHeroLead:'Educational content from LABS for patients and families.',searchPlaceholder:'Search here',searchButton:'Search',noResults:'No content was found for that term.',
  quotePageTitle:'Test quote',quotePageLead:'Search, select your tests and generate a PDF quotation.',quoteKicker:'TEST QUOTATION',quoteTitle:'Search and quote your tests.',quoteIntro:'Search for a test, add it individually to your quotation and review the total automatically.',examSearchPlaceholder:'Search test by name',clearSearch:'Clear',selectedTitle:'Selected tests',selectedLabel:'selected',totalLabel:'TOTAL',clientData:'Client information',fullName:'Full name',idNumber:'ID number',email:'Email',phone:'Phone',generatePdf:'GENERATE PDF QUOTATION',pdfNote:'The PDF will include selected tests, prices, total, date and your information.',add:'Add',added:'Added',remove:'Remove',emptySelected:'You have not added any tests yet.',noExams:'No tests were found with that name.',
  footerNear:'HUMANLABS is always close to you.',footerExplore:'EXPLORE',footerLabs:'LABS',footerWho:'About us',footerLocations:'Locations',footerContact:'CONTACT',whatsapp:'WhatsApp',copyright:'© 2026 HUMANLABS. All Rights Reserved',diagnostics:'Diagnostic Medicine',privacyTitle:'Privacy',privacyText:'This site uses necessary cookies to operate and optional cookies to improve your experience.',saveCookies:'SAVE AND ACCEPT',
  pdfTitle:'TEST QUOTATION',pdfClient:'CLIENT INFORMATION',pdfExam:'TEST',pdfPrice:'PRICE',pdfTotal:'TOTAL',pdfDisclaimer:'This document is a quotation request and is not a tax invoice.',pdfConfirm:'Prices shown according to the quotation catalog used by this site; please confirm conditions with LABS.',pdfGenerated:'PDF generated successfully.',pdfLoad:'The PDF generator could not be loaded. Please check your internet connection.',
  alertName:'Enter your full name.',alertCedula:'The ID number must contain 10 digits.',alertEmail:'Enter a valid email address.',alertPhone:'Enter a valid phone number.',alertExam:'Add at least one test to the quotation.'
 }
};
let currentLang=localStorage.getItem('labs-language')||'es';
const t=k=>(I18N[currentLang]&&I18N[currentLang][k])||I18N.es[k]||k;
function applyLanguage(){document.documentElement.lang=currentLang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(I18N[currentLang][key]!==undefined)el.textContent=I18N[currentLang][key]});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const key=el.dataset.i18nPlaceholder;if(I18N[currentLang][key]!==undefined)el.placeholder=I18N[currentLang][key]});document.querySelectorAll('[data-lang-toggle]').forEach(b=>b.textContent=currentLang==='es'?'ES | EN':'EN | ES');renderExamResults(document.getElementById('examSearch')?.value||'');renderSelected();localStorage.setItem('labs-language',currentLang);}
function toggleLanguage(){currentLang=currentLang==='es'?'en':'es';applyLanguage();}
function initLanguage(){document.querySelectorAll('[data-lang-toggle]').forEach(b=>b.addEventListener('click',toggleLanguage));applyLanguage();}
function initMenu(){const btn=document.getElementById('menuBtn'),nav=document.getElementById('nav');if(btn&&nav){btn.addEventListener('click',()=>{const open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');btn.setAttribute('aria-expanded','false')}))}}
function initCookie(){const c=document.getElementById('cookie');if(c&&!localStorage.getItem('labs-cookie'))c.classList.add('show');document.getElementById('acceptCookies')?.addEventListener('click',()=>{localStorage.setItem('labs-cookie','1');c?.classList.remove('show')})}
function renderExamResults(q=''){const box=document.getElementById('examResults');if(!box)return;const term=q.trim().toLowerCase();const list=examsSearch.filter(x=>!term||x.name.toLowerCase().includes(term)).slice(0,80);box.innerHTML=list.map(x=>`<div class="examRow"><div><strong>${esc(x.name)}</strong><span>${x.price}</span></div><button type="button" class="btn smallBtn" data-add-exam="${x.id}" ${state.selected.has(x.id)?'disabled':''}>${state.selected.has(x.id)?t('added'):t('add')}</button></div>`).join('')||`<p class="emptyState">${t('noExams')}</p>`;box.querySelectorAll('[data-add-exam]').forEach(b=>b.addEventListener('click',()=>{state.selected.add(Number(b.dataset.addExam));renderExamResults(document.getElementById('examSearch')?.value||'');renderSelected()}))}
function renderSelected(){const box=document.getElementById('selectedExams'),total=document.getElementById('quoteTotalInline'),count=document.getElementById('selectedCount');if(!box)return;const ids=[...state.selected],arr=ids.map(i=>exams[i]),sum=arr.reduce((a,x)=>a+money(x.price),0);if(total)total.textContent=fmt(sum);if(count)count.textContent=String(arr.length);box.innerHTML=arr.length?arr.map((x,i)=>`<div class="selectedRow"><div><strong>${esc(x.name)}</strong><span>${x.price}</span></div><button type="button" class="removeExam" data-remove="${ids[i]}">${t('remove')}</button></div>`).join(''):`<p class="emptyState">${t('emptySelected')}</p>`;box.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{state.selected.delete(Number(b.dataset.remove));renderExamResults(document.getElementById('examSearch')?.value||'');renderSelected()}))}
function validForm(){const form=document.getElementById('quoteForm');if(!form)return false;const name=form.name.value.trim(),ced=form.cedula.value.trim(),email=form.email.value.trim(),phone=form.phone.value.trim();if(name.length<3){alert(t('alertName'));form.name.focus();return false}if(!/^\d{10}$/.test(ced)){alert(t('alertCedula'));form.cedula.focus();return false}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){alert(t('alertEmail'));form.email.focus();return false}if(!/^\d{7,15}$/.test(phone.replace(/\s|[-+()]/g,''))){alert(t('alertPhone'));form.phone.focus();return false}if(!state.selected.size){alert(t('alertExam'));return false}return true}
function imageData(url){return new Promise(resolve=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{try{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);resolve(c.toDataURL('image/jpeg',.9))}catch(e){resolve(null)}};img.onerror=()=>resolve(null);img.src=url})}
async function generatePDF(){if(!validForm())return;if(!window.jspdf){alert(t('pdfLoad'));return}const {jsPDF}=window.jspdf,doc=new jsPDF();const green=[47,144,142],orange=[239,125,50],dark=[36,59,58];const data=new FormData(document.getElementById('quoteForm')),selected=[...state.selected].map(i=>exams[i]),total=selected.reduce((a,x)=>a+money(x.price),0),now=new Date(),date=now.toLocaleDateString(currentLang==='es'?'es-EC':'en-US'),code='LABS-'+now.getFullYear()+String(now.getMonth()+1).padStart(2,'0')+String(now.getDate()).padStart(2,'0')+'-'+Math.floor(1000+Math.random()*9000);doc.setFillColor(...green);doc.rect(0,0,210,30,'F');const logo=await imageData('https://labs.ec/wp-content/uploads/2020/10/logo.jpg');if(logo){try{doc.addImage(logo,'JPEG',14,7,48,16)}catch(e){doc.setTextColor(255,255,255);doc.setFontSize(22);doc.setFont('helvetica','bold');doc.text('LABS',14,20)}}else{doc.setTextColor(255,255,255);doc.setFontSize(22);doc.setFont('helvetica','bold');doc.text('LABS',14,20)}doc.setTextColor(255,255,255);doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text(currentLang==='es'?'MEDICINA DIAGNÓSTICA':'DIAGNOSTIC MEDICINE',14,26);doc.setFontSize(15);doc.setFont('helvetica','bold');doc.text(t('pdfTitle'),196,14,{align:'right'});doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text(date+' · '+code,196,22,{align:'right'});let y=44;doc.setTextColor(...dark);doc.setFontSize(12);doc.setFont('helvetica','bold');doc.text(t('pdfClient'),14,y);y+=9;doc.setFontSize(9);doc.setFont('helvetica','normal');[[t('fullName'),data.get('name')],[t('idNumber'),data.get('cedula')],[t('email'),data.get('email')],[t('phone'),data.get('phone')]].forEach(([k,v])=>{doc.setFont('helvetica','bold');doc.text(k+':',14,y);doc.setFont('helvetica','normal');doc.text(String(v),58,y);y+=6});y+=5;doc.setFillColor(...green);doc.rect(14,y-5,182,9,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.text(t('pdfExam'),18,y+1);doc.text(t('pdfPrice'),192,y+1,{align:'right'});y+=12;doc.setTextColor(...dark);doc.setFont('helvetica','normal');selected.forEach((x,idx)=>{if(y>275){doc.addPage();y=20}if(idx%2===0){doc.setFillColor(245,249,248);doc.rect(14,y-5,182,9,'F')}doc.text(x.name,18,y+1);doc.text(x.price,192,y+1,{align:'right'});y+=9});y+=6;doc.setDrawColor(...orange);doc.line(120,y,196,y);y+=10;doc.setFont('helvetica','bold');doc.setFontSize(13);doc.setTextColor(...green);doc.text(t('pdfTotal'),145,y);doc.setTextColor(...dark);doc.text(fmt(total),192,y,{align:'right'});y+=18;doc.setFontSize(8);doc.setFont('helvetica','normal');doc.setTextColor(100,100,100);doc.text(t('pdfDisclaimer'),14,y);doc.text(t('pdfConfirm'),14,y+5);doc.text('HUMANLABS · '+(currentLang==='es'?'Medicina Diagnóstica':'Diagnostic Medicine')+' · (+593) 98 509 0215 · info@labs.ec',14,y+14);doc.save(code+'.pdf');const msg=document.getElementById('quoteMsg');if(msg)msg.textContent=t('pdfGenerated')}
function initQuote(){const search=document.getElementById('examSearch');if(!search)return;renderExamResults();renderSelected();search.addEventListener('input',()=>renderExamResults(search.value));document.getElementById('clearSearch')?.addEventListener('click',()=>{search.value='';renderExamResults()});document.getElementById('quoteForm')?.addEventListener('submit',e=>{e.preventDefault();generatePDF()})}
function initArticle(){
 const box=document.getElementById('article');
 if(!box)return;
 const path=window.location.pathname.replace(/\\/g,'/').replace(/\/$/,'');
 const slug=path.split('/').pop();
 const n=notes.find(x=>x.slug===slug);
 if(!n){box.innerHTML='<p class="emptyState">No encontramos esta nota.</p>';return;}
 const imgPath='../../'+n.img;
 const body=(n.body||[]).map((p,i)=>{
   const text=esc(p);
   if(i===2 && n.slug==='higado-el-filtro-natural-del-cuerpo') return '<h2>Principales funciones del hígado</h2><p>'+text+'</p>';
   return '<p>'+text+'</p>';
 }).join('');
 box.innerHTML=`<div class="articleMeta">${esc(n.date)} · ${esc(n.tag)} · LABS</div><h1>${esc(n.title)}</h1><p class="lead">${esc(n.intro)}</p><img class="articleImage" src="${imgPath}" alt="${esc(n.title)}"><div class="articleBody">${body}</div><p style="margin-top:42px"><a class="btn secondary" href="../">← <span data-i18n="backToNotes">Volver a Notas de salud</span></a></p>`;
}
function initHome(){const slides=[...document.querySelectorAll('.slide')],dots=[...document.querySelectorAll('.dots button')];if(slides.length){let idx=0;const go=i=>{idx=i;slides.forEach((s,j)=>s.classList.toggle('active',j===i));dots.forEach((d,j)=>d.classList.toggle('active',j===i))};dots.forEach(d=>d.addEventListener('click',()=>go(+d.dataset.i)));setInterval(()=>go((idx+1)%slides.length),6000)}}
document.addEventListener('DOMContentLoaded',()=>{initMenu();initCookie();initLanguage();initQuote();initHome();initArticle()});
