const exams=[
['Ácido úrico','$3,30'],['Albúmina','$3,30'],['Amilasa','$4,00'],['Aglutinaciones febriles','$7,00'],['ASTO - Antiestreptolisina','$8,80'],['Alfa feto proteínas - AFP','$13,28'],['Ácido fólico','$13,00'],['ACTIN F. IgA / ACTIN','$28,60'],['ACTIN IgG','$28,60'],['ANCA C-P','$40,00'],['ASCA IgG','$25,50'],['ASCA IgA','$25,50'],['Antitrombina','$39,61'],['Apolipoproteína A1','$15,40'],['Apolipoproteína B','$9,36'],['BUN (incluye urea)','$6,09'],['Creatinina','$3,30'],['Colesterol total','$3,30'],['Colesterol HDL','$5,50'],['Colesterol LDL','$5,60'],['Coprocultivo (heces)','$22,00'],['Calcio','$4,00'],['CA 125 (ovario, útero)','$15,40'],['Ceruloplasmina','$35,07'],['Calprotectina','$36,40'],['Calcio iónico','$8,00'],['Cloro','$3,38'],['Cardiolipina IgG','$24,44'],['Cardiolipina IgM','$24,44'],['CK MB-CPK','$13,52'],['Creatinina (orina)','$6,09'],['Colinesterasa','$4,40'],['Interleukina 6','$34,00'],['Insulina plasmática en ayunas','$14,30'],['IgG por nefelometría','$16,00'],['IgM por nefelometría','$17,00'],['IgA por nefelometría','$17,00'],['IgE total','$16,00'],['Influenza A/B/H1N1 por PCR GeneXpert','$188,37'],['Influenza A/B antígeno','$28,00'],['Insulina 2h post prandial','$34,00'],['KOH','$13,20'],['Kappa (orina)','$27,63'],['Kappa 24h','$28,60'],['Lipasa','$4,40'],['LDH (deshidrogenasa láctica)','$4,40'],['Linfocitos B (CD19-CD20)','$80,00'],['Linfocitos NK (CD16-CD56)','$48,30'],['Lipoproteína A','$16,00'],['Litio','$16,00'],['Lactoferrina','$20,00'],['Norovirus','$40,00'],['Osmolalidad','$14,49'],['Osteocalcina','$50,72'],['Oxalato urinario','$46,20'],['Opiáceos cuantitativa','$11,59'],['Plaquetas','$6,00'],['Prueba de Coombs directa','$9,00'],['Prueba de Coombs indirecta','$9,00'],['Parasitoscópico concentración (heces)','$6,00'],['PSA total','$16,93'],['PSA libre','$25,30'],['Potasio','$4,00'],['Pro-BNP','$65,00'],['Procalcitonina','$74,38'],['Prealbúmina','$30,00'],['Prolactina','$12,00'],['Progesterona','$12,00'],['Rotavirus','$13,00'],['R. de Widal y Weill Felix','$7,00'],['Factor reumatoideo por nefelometría','$16,00'],['RPR','$5,00'],['Rubeola IgG','$16,72'],['Rubeola IgM','$16,72'],['Sangre oculta - HB humana','$7,10'],['Sodio','$4,00'],['Sodio (orina)','$4,00'],['Strept-A','$13,20'],['Salmonella antígeno','$14,00'],['Urea','$3,30'],['Urocultivo (orina)','$18,00'],['Urea 24h','$6,30'],['V.D.R.L.','$5,50'],['Vitamina B12','$13,00'],['VLDL colesterol','$6,30'],['V.D.R.L. cuantitativo','$9,00'],['Varicela zóster IgG','$28,00'],['Varicela zóster IgM','$21,25'],['Vitamina D total','$32,00'],['Vitamina E','$65,10'],['Virus sincitial respiratorio','$36,75'],['Ziehl Neelsen','$7,20'],['Zinc','$35,00'],['Zika virus IgG','$100,49'],['Zika virus IgM','$75,74']
].map(([name,price])=>({name,price}));
const notes=[
{slug:'el-estres-un-enemigo-silencioso-que-afecta-nuestra-salud-fisica-y-mental',title:'El estrés: Un enemigo silencioso que afecta nuestra salud física y mental',date:'07 Nov',tag:'Labs · Salud',img:'assets/labs-inicio-2.jpeg',intro:'La Organización Mundial de la Salud (OMS) define el estrés como cualquier tipo de cambio que provoca agotamiento físico, emocional o psicológico.',body:[`La Organización Mundial de la Salud (OMS) define el estrés como cualquier tipo de cambio que provoca agotamiento físico, emocional o psicológico. Según la entidad, se trata de una respuesta natural del cuerpo humano ante situaciones que requieren una acción rápida.`,`Aunque el estrés puede surgir frente a cualquier desafío, es un fenómeno cotidiano en la vida moderna. Cuando se convierte en algo crónico puede tener repercusiones en la salud.`,`El cuerpo reacciona al estrés liberando hormonas como el cortisol, que activan el estado de alerta, tensionan los músculos y aceleran la respiración y el ritmo cardíaco. Dolores de cabeza, malestar estomacal, dolor de espalda e insomnio son algunas de sus manifestaciones.`,`Para evaluar su impacto, LABS señala la utilidad de perfiles hormonales y pruebas específicas, siempre dentro de una evaluación médica.`,`Aprender a manejar el estrés mejora la calidad de vida. El ejercicio regular, las técnicas de relajación y actividades que generen bienestar pueden ayudar a reducir la tensión.`]},
{slug:'higado-el-filtro-natural-del-cuerpo',title:'Hígado, el «filtro» natural del cuerpo',date:'05 Sep',tag:'Hígado · Labs',img:'assets/labs-inicio-1.jpeg',intro:'Mantenerlo sano a través de una buena alimentación es vital.',body:[`El hígado, un órgano esencial, tiene un papel crucial en la actividad metabólica. Se ubica en la parte superior derecha de la cavidad abdominal y cumple funciones vitales para el bienestar general.`,`Es responsable de regular sustancias químicas en la sangre, producir bilis y procesar sustancias que llegan desde el aparato digestivo.`,`Principales funciones del hígado: eliminación de toxinas, metabolización de medicamentos, secreción de bilis y almacenamiento de nutrientes.`,`La prevención es clave. Una alimentación equilibrada, moderar el consumo de grasas y alimentos procesados, evitar el exceso de alcohol y mantener actividad física son medidas importantes.`,`En LABS se puede realizar una prueba de función hepática para evaluar proteínas, bilirrubinas y enzimas hepáticas, de acuerdo con la indicación médica.`]},
{slug:'rinones-los-heroes-ocultos-de-nuestro-cuerpo',title:'Riñones: los héroes ocultos de nuestro cuerpo',date:'23 Jul',tag:'Labs',img:'assets/labs-inicio-2.jpeg',intro:'La hidratación, el ejercicio y una alimentación baja en sal son fundamentales para su cuidado.',body:[`Los riñones son dos órganos con una tarea primordial: filtrar la sangre y eliminar desechos. También participan en funciones hormonales y en el equilibrio del organismo.`,`Cada día filtran grandes cantidades de sangre para producir orina y ayudar a mantener el equilibrio de agua y minerales.`,`Los malos hábitos pueden afectar la salud renal. Entre ellos están una dieta alta en sal, ingerir demasiada azúcar, fumar, beber poca agua, la inactividad física y el consumo excesivo de alcohol.`,`Los exámenes de sangre y orina permiten evaluar el funcionamiento renal. Entre los análisis mencionados por LABS están creatinina, BUN, cistatina C y evaluaciones de proteínas en orina.`]},
{slug:'4-sintomas-que-debes-saber-sobre-el-dengue',title:'4 síntomas que debes saber sobre el dengue',date:'05 Mar',tag:'Labs · Nacionales',img:'assets/labs-inicio-2.jpeg',intro:'Fiebre alta, dolor de cabeza, dolor muscular y molestias detrás de los ojos son síntomas que requieren atención.',body:[`Los cuatro síntomas destacados son fiebre alta, dolor de cabeza, dolor muscular y molestias detrás de los ojos. Ante síntomas compatibles es importante acudir a un médico y evitar la automedicación.`,`Las pruebas de laboratorio desempeñan un papel fundamental en el diagnóstico preciso del dengue. LABS cuenta con pruebas específicas como Dengue anti IgG, Dengue anti IgM y antígeno NS1, según la indicación médica.`,`Las medidas preventivas incluyen eliminar aguas estancadas, usar repelentes, instalar mosquiteros y acudir a consulta ante la presencia de síntomas.`,`La prevención, la detección temprana y el tratamiento adecuado son herramientas importantes en la lucha contra el dengue.`]},
{slug:'perdiendo-peso-que-examenes-de-laboratorio-necesito',title:'Perdiendo peso, ¿qué exámenes de laboratorio necesito?',date:'05 Feb',tag:'Exámenes · Labs · Salud',img:'assets/labs-inicio-1.jpeg',intro:'Bajar de peso de manera saludable requiere prevención, alimentación equilibrada, ejercicio y seguimiento médico.',body:[`La medicina preventiva juega un papel importante. Los chequeos y exámenes básicos de sangre, heces y orina pueden aportar información sobre el estado del organismo.`,`Un estilo de vida saludable combina dieta equilibrada, ejercicio regular y controles médicos periódicos.`,`Los análisis clínicos pueden revelar aspectos como niveles de glucosa, perfil lipídico e intolerancias alimentarias, entre otros indicadores.`,`Los resultados deben interpretarse con el acompañamiento de profesionales de la salud.`]},
{slug:'7-examenes-basicos-que-debes-realizarte-en-el-ano',title:'7 exámenes básicos que debes realizarte en el año',date:'19 Ene',tag:'Exámenes · Labs · Salud',img:'assets/labs-inicio-1.jpeg',intro:'Los chequeos preventivos y análisis completos aportan información valiosa sobre el estado general de salud.',body:[`El hemograma completo evalúa las células sanguíneas y es uno de los análisis básicos más habituales.`,`El perfil lipídico permite conocer niveles de colesterol y triglicéridos. La glucosa en sangre está relacionada con la detección y control de diabetes.`,`Los marcadores inflamatorios aportan información sobre la presencia de inflamación. También pueden evaluarse vitaminas y minerales.`,`El elemental físico químico de orina y el coproparasitario forman parte de los análisis básicos descritos por LABS.`,`La preparación depende del examen y debe seguir las indicaciones del laboratorio y del profesional de salud.`]},
{slug:'estres-dolor-abdominal-gases-estrenimiento',title:'¿Cómo los exámenes revelan el impacto del estrés en tu salud?',date:'11 Ene',tag:'Exámenes · Labs · Salud',img:'assets/labs-inicio-2.jpeg',intro:'Los niveles altos de estrés pueden relacionarse con trastornos gastrointestinales y otros síntomas.',body:[`Entre los síntomas descritos están hinchazón abdominal, dolor de estómago, estreñimiento, opresión estomacal, falta de apetito y dispepsia.`,`La evaluación médica puede acompañarse de grupos de exámenes como cortisol, perfil hormonal, muestras fecales, pruebas de inflamación, función hepática y nutrientes.`,`La combinación de estas pruebas puede brindar al especialista información para valorar el estado de salud gastrointestinal.`]},
{slug:'que-se-puede-ver-en-un-hemograma',title:'¿Qué se puede ver en un hemograma?',date:'22 Dic',tag:'Exámenes · Labs · Salud',img:'assets/labs-inicio-1.jpeg',intro:'El hemograma es uno de los análisis más comunes y aporta información sobre las células sanguíneas.',body:[`El hemograma permite observar el comportamiento de glóbulos rojos, glóbulos blancos y plaquetas. Estos parámetros ayudan a valorar distintas condiciones.`,`Realizarse controles puede contribuir a identificar alteraciones en etapas tempranas. La interpretación debe estar a cargo de un médico.`,`Para realizar un hemograma se requiere una muestra de sangre y, según la información publicada por LABS, no es necesario estar en ayunas.`]},
{slug:'los-examenes-de-laboratorio-son-necesarios-y-primordiales',title:'Los exámenes de laboratorio son necesarios y primordiales',date:'15 Dic',tag:'Labs · Salud',img:'assets/labs-inicio-2.jpeg',intro:'Las pruebas de laboratorio aportan información para el diagnóstico, seguimiento y prevención.',body:[`Los exámenes de laboratorio se realizan a partir de muestras como sangre, orina y heces, y pueden ayudar a descubrir diversas afecciones.`,`Las pruebas diagnósticas son una herramienta de apoyo para las decisiones médicas y permiten evaluar diferentes aspectos fisiológicos y bioquímicos.`,`La variedad de exámenes disponibles permite personalizar el enfoque de atención y contribuir a la prevención y manejo de distintas afecciones.`]},
{slug:'el-vih-y-el-sida-son-lo-mismo',title:'¿El VIH y el SIDA son lo mismo?',date:'01 Dic',tag:'Exámenes · Labs · Salud',img:'assets/labs-inicio-1.jpeg',intro:'VIH y SIDA están relacionados, pero no significan lo mismo.',body:[`El VIH es el virus que causa la infección, mientras que el SIDA es un síndrome que puede aparecer en una etapa avanzada de la infección.`,`El virus puede transmitirse mediante determinados fluidos corporales y existen vías de transmisión sexual, sanguínea y vertical.`,`Los exámenes de laboratorio son importantes para detectar y hacer seguimiento de la infección y de la respuesta al tratamiento.`]}
];
function rootPrefix(){const p=location.pathname; if(/\/noticias\/[^/]+\/?$/.test(p)) return '../../'; if(/\/(noticias|nosotros|contacto)\/?$/.test(p)) return '../'; return '';}
function header(active=''){const r=rootPrefix();return `<div class="topbar"><div class="wrap"><span>Av. Abel Romeo Castillo y Juan Tanca Marengo, Torre Médica 2, piso 4, consultorios 417 y 418</span><span>(+593) 98 509 0215 · info@labs.ec</span></div></div><header class="header"><div class="wrap navwrap"><a class="brand" href="${r}index.html"><div class="brandMark">LAB<span>S</span><i>+</i></div><small>MEDICINA<br>DIAGNÓSTICA</small></a><button class="menuBtn" id="menuBtn">☰</button><nav class="nav" id="nav"><a class="${active==='inicio'?'active':''}" href="${r}index.html">Inicio</a><a class="${active==='nosotros'?'active':''}" href="${r}nosotros/">Nosotros</a><a class="${active==='noticias'?'active':''}" href="${r}noticias/">Notas de salud</a><a class="${active==='contacto'?'active':''}" href="${r}contacto/">Contactos</a><a class="login" href="https://app.labs.ec/" target="_blank" rel="noopener">Login</a></nav></div></header>`}
function footer(){const r=rootPrefix();return `<footer class="footer"><div class="wrap footerGrid"><div><div class="brand"><div class="brandMark" style="color:#fff">LAB<span>S</span><i>+</i></div><small style="color:#c5dcda">MEDICINA<br>DIAGNÓSTICA</small></div><p>HUMANLABS siempre cerca de ti.</p></div><div><h4>EXPLORA</h4><a href="${r}index.html">Inicio</a><a href="${r}nosotros/">Nosotros</a><a href="${r}noticias/">Notas de salud</a><a href="${r}contacto/">Contactos</a></div><div><h4>LABS</h4><a href="${r}nosotros/">Quiénes somos</a><a href="${r}contacto/">Sedes</a><a href="mailto:info@labs.ec?subject=Trabaja%20con%20LABS">Trabaja con nosotros</a></div><div><h4>CONTACTO</h4><a href="tel:+593985090215">+593 98 509 0215</a><a href="mailto:info@labs.ec">info@labs.ec</a><a href="https://app.labs.ec/" target="_blank">Acceder a resultados ↗</a></div></div><div class="wrap copyright"><span>© 2026 HUMANLABS. Todos los Derechos Reservados</span><span>Medicina Diagnóstica</span></div></footer><a class="whatsapp" href="https://wa.me/593985090215" target="_blank" aria-label="WhatsApp">WA</a><div class="cookie" id="cookie"><h4>Privacy Overview</h4><p>Este sitio utiliza cookies necesarias para funcionar y cookies opcionales para mejorar la experiencia.</p><button class="btn primary" id="acceptCookies">GUARDAR Y ACEPTAR</button></div>`}
function init(){document.getElementById('menuBtn')?.addEventListener('click',()=>document.getElementById('nav').classList.toggle('open'));document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>document.getElementById('nav')?.classList.remove('open')));if(!localStorage.getItem('labs-cookie'))document.getElementById('cookie')?.classList.add('show');document.getElementById('acceptCookies')?.addEventListener('click',()=>{localStorage.setItem('labs-cookie','1');document.getElementById('cookie').classList.remove('show')})}
window.notes=notes;window.header=header;window.footer=footer;window.init=init;

const examsSearch = exams.map((x,i)=>({...x,id:i}));
const state={selected:new Set()};
const money=s=>Number(String(s).replace('$','').replace(',','.'));
const fmt=n=>'$'+n.toFixed(2).replace('.',',');
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function initMenu(){const btn=document.getElementById('menuBtn'),nav=document.getElementById('nav');if(btn&&nav){btn.addEventListener('click',()=>{nav.classList.toggle('open');btn.setAttribute('aria-expanded',nav.classList.contains('open'));});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}}
function initCookie(){const c=document.getElementById('cookie');if(c&&!localStorage.getItem('labs-cookie'))c.classList.add('show');document.getElementById('acceptCookies')?.addEventListener('click',()=>{localStorage.setItem('labs-cookie','1');c?.classList.remove('show')})}
function renderExamResults(q=''){
 const box=document.getElementById('examResults'); if(!box)return;
 const term=q.trim().toLowerCase(); const list=examsSearch.filter(x=>!term||x.name.toLowerCase().includes(term)).slice(0,80);
 box.innerHTML=list.map(x=>`<div class="examRow"><div><strong>${esc(x.name)}</strong><span>${x.price}</span></div><button type="button" class="btn smallBtn" data-add-exam="${x.id}" ${state.selected.has(x.id)?'disabled':''}>${state.selected.has(x.id)?'Agregado':'Agregar'}</button></div>`).join('') || '<p class="emptyState">No encontramos exámenes con ese nombre.</p>';
 box.querySelectorAll('[data-add-exam]').forEach(b=>b.addEventListener('click',()=>{state.selected.add(Number(b.dataset.addExam));renderExamResults(document.getElementById('examSearch')?.value||'');renderSelected();}));
}
function renderSelected(){
 const box=document.getElementById('selectedExams'), total=document.getElementById('quoteTotalInline'), count=document.getElementById('selectedCount'); if(!box)return;
 const arr=[...state.selected].map(i=>exams[i]); const sum=arr.reduce((a,x)=>a+money(x.price),0);
 if(total)total.textContent=fmt(sum); if(count)count.textContent=String(arr.length);
 box.innerHTML=arr.length?arr.map((x,i)=>`<div class="selectedRow"><div><strong>${esc(x.name)}</strong><span>${x.price}</span></div><button type="button" class="removeExam" data-remove="${[...state.selected][i]}">Eliminar</button></div>`).join(''):'<p class="emptyState">Aún no has agregado exámenes.</p>';
 box.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{state.selected.delete(Number(b.dataset.remove));renderExamResults(document.getElementById('examSearch')?.value||'');renderSelected();}));
}
function validForm(){
 const form=document.getElementById('quoteForm'); if(!form)return false;
 const name=form.name.value.trim(), ced=form.cedula.value.trim(), email=form.email.value.trim(), phone=form.phone.value.trim();
 if(name.length<3){alert('Ingresa tu nombre completo.');form.name.focus();return false}
 if(!/^\d{10}$/.test(ced)){alert('La cédula debe contener 10 dígitos.');form.cedula.focus();return false}
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){alert('Ingresa un correo electrónico válido.');form.email.focus();return false}
 if(!/^\d{7,15}$/.test(phone.replace(/\s|[-+()]/g,''))){alert('Ingresa un teléfono válido.');form.phone.focus();return false}
 if(!state.selected.size){alert('Agrega al menos un examen a la cotización.');return false}
 return true;
}
function imageData(url){return new Promise(resolve=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{try{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);resolve(c.toDataURL('image/jpeg',.9))}catch(e){resolve(null)}};img.onerror=()=>resolve(null);img.src=url;});}
async function generatePDF(){
 if(!validForm())return; if(!window.jspdf){alert('No se pudo cargar el generador PDF. Revisa tu conexión a internet.');return}
 const {jsPDF}=window.jspdf; const doc=new jsPDF(); const green=[47,144,142], orange=[239,125,50], dark=[36,59,58];
 const data=new FormData(document.getElementById('quoteForm')); const selected=[...state.selected].map(i=>exams[i]); const total=selected.reduce((a,x)=>a+money(x.price),0); const now=new Date(); const date=now.toLocaleDateString('es-EC'); const code='LABS-'+now.getFullYear()+String(now.getMonth()+1).padStart(2,'0')+String(now.getDate()).padStart(2,'0')+'-'+Math.floor(1000+Math.random()*9000);
 doc.setFillColor(...green);doc.rect(0,0,210,30,'F');
 const logo=await imageData('https://labs.ec/wp-content/uploads/2020/10/logo.jpg');
 if(logo){try{doc.addImage(logo,'JPEG',14,7,48,16)}catch(e){doc.setTextColor(255,255,255);doc.setFontSize(22);doc.text('LABS',14,20)}}else{doc.setTextColor(255,255,255);doc.setFontSize(22);doc.setFont('helvetica','bold');doc.text('LABS',14,20)}
 doc.setTextColor(255,255,255);doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text('MEDICINA DIAGNÓSTICA',14,26);doc.setFontSize(15);doc.setFont('helvetica','bold');doc.text('COTIZACIÓN DE EXÁMENES',196,14,{align:'right'});doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text(date+' · '+code,196,22,{align:'right'});
 let y=44;doc.setTextColor(...dark);doc.setFontSize(12);doc.setFont('helvetica','bold');doc.text('DATOS DEL CLIENTE',14,y);y+=9;doc.setFontSize(9);doc.setFont('helvetica','normal');
 [['Nombre completo',data.get('name')],['Cédula',data.get('cedula')],['Correo',data.get('email')],['Teléfono',data.get('phone')]].forEach(([k,v])=>{doc.setFont('helvetica','bold');doc.text(k+':',14,y);doc.setFont('helvetica','normal');doc.text(String(v),52,y);y+=6});
 y+=5;doc.setFillColor(...green);doc.rect(14,y-5,182,9,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.text('EXAMEN',18,y+1);doc.text('PRECIO',192,y+1,{align:'right'});y+=12;doc.setTextColor(...dark);doc.setFont('helvetica','normal');
 selected.forEach((x,idx)=>{if(y>275){doc.addPage();y=20} if(idx%2===0){doc.setFillColor(245,249,248);doc.rect(14,y-5,182,9,'F')}doc.text(x.name,18,y+1);doc.text(x.price,192,y+1,{align:'right'});y+=9});
 y+=6;doc.setDrawColor(...orange);doc.line(120,y,196,y);y+=10;doc.setFont('helvetica','bold');doc.setFontSize(13);doc.setTextColor(...green);doc.text('TOTAL',145,y);doc.setTextColor(...dark);doc.text(fmt(total),192,y,{align:'right'});
 y+=18;doc.setFontSize(8);doc.setFont('helvetica','normal');doc.setTextColor(100,100,100);doc.text('Este documento corresponde a una solicitud de cotización y no constituye una factura fiscal.',14,y);doc.text('Precios mostrados según el catálogo de cotización utilizado por este sitio; confirme condiciones con LABS.',14,y+5);doc.text('HUMANLABS · Medicina Diagnóstica · (+593) 98 509 0215 · info@labs.ec',14,y+14);
 doc.save(code+'.pdf');
 const msg=document.getElementById('quoteMsg');if(msg)msg.textContent='PDF generado correctamente.';
}
function initQuote(){
 const search=document.getElementById('examSearch');if(!search)return;
 renderExamResults();renderSelected();search.addEventListener('input',()=>renderExamResults(search.value));document.getElementById('clearSearch')?.addEventListener('click',()=>{search.value='';renderExamResults()});document.getElementById('quoteForm')?.addEventListener('submit',e=>{e.preventDefault();generatePDF()});
 document.querySelectorAll('[data-scroll-quote]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();document.getElementById('cotizador')?.scrollIntoView({behavior:'smooth'})}));
}
function initHome(){
 const slides=[...document.querySelectorAll('.slide')],dots=[...document.querySelectorAll('.dots button')];if(slides.length){let idx=0;const go=i=>{idx=i;slides.forEach((s,j)=>s.classList.toggle('active',j===i));dots.forEach((d,j)=>d.classList.toggle('active',j===i))};dots.forEach(d=>d.onclick=()=>go(+d.dataset.i));setInterval(()=>go((idx+1)%slides.length),6000)}
 const home=document.getElementById('homeNotes');if(home)home.innerHTML=notes.slice(0,4).map(n=>`<a class="noteCard" href="noticias/${n.slug}/"><img src="${n.img}" alt="${esc(n.title)}"><div class="noteBody"><div class="date">${n.date}</div><h3>${esc(n.title)}</h3><p>${esc(n.intro)}</p></div></a>`).join('');
}
document.addEventListener('DOMContentLoaded',()=>{initMenu();initCookie();initQuote();initHome();});
